-- PROVENANCE: This file is AUTO-GENERATED by Aeneas. Do not edit by hand.
--
-- Pipeline (see ../.ignore/aeneas/reproduce.sh and SPIKE.md):
--   charon cargo --preset=aeneas \
--     --start-from 'crate::encode' --start-from 'crate::encoded_len' -- --lib
--   aeneas -backend lean -namespace BijouRust bijou64_enc.llbc
--
-- Tooling: Charon 0.1.212, Aeneas 0.1.0 (github:aeneasverif/aeneas
--   rev bf13c42e7c34d07fc396baffad39c93023b12914), rustc nightly-2026-06-01.
--
-- `decode` is intentionally NOT translated here: its `&[a, ..]` subslice
-- rest-patterns are unsupported by this Aeneas version. `decode` is
-- verified separately with Kani (see ../bijou64/ Kani harnesses).
--
-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [bijou64]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace BijouRust

/-- [core::num::{u64}::saturating_mul]:
    Source: '/rustc/library/core/src/num/uint_macros.rs', lines 2516:8-2516:60
    Name pattern: [core::num::{u64}::saturating_mul]
    Visibility: public -/
@[rust_fun "core::num::{u64}::saturating_mul"]
axiom core.num.U64.saturating_mul : Std.U64 → Std.U64 → Result Std.U64

/-- [alloc::vec::{alloc::vec::Vec<T>}::truncate]:
    Source: '/rustc/library/alloc/src/vec/mod.rs', lines 1814:4-1814:42
    Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::truncate]
    Visibility: public -/
@[rust_fun "alloc::vec::{alloc::vec::Vec<@T>}::truncate"]
axiom alloc.vec.Vec.truncate
  {T : Type} (A : Type) :
  alloc.vec.Vec T → Std.Usize → Result (alloc.vec.Vec T)

/-- [bijou64::TAG_THRESHOLD]
    Source: 'bijou64/src/lib.rs', lines 86:0-86:30 -/
@[global_simps, irreducible] def TAG_THRESHOLD : Std.U8 := 248#u8

/-- [bijou64::NUM_TIERS]
    Source: 'bijou64/src/lib.rs', lines 89:0-89:27 -/
@[global_simps, irreducible] def NUM_TIERS : Std.Usize := 8#usize

/-- [bijou64::tier_offset]: loop body 0:
    Source: 'bijou64/src/lib.rs', lines 107:4-111:5 -/
@[rust_loop_body]
def tier_offset_loop.body
  (n : Std.Usize) (result : Std.U64) (power : Std.U64) (i : Std.Usize) :
  Result (ControlFlow (Std.U64 × Std.U64 × Std.Usize) Std.U64)
  := do
  if i <= n
  then
    let power1 ← core.num.U64.saturating_mul power 256#u64
    let result1 ← lift (core.num.U64.saturating_add result power1)
    let i1 ← i + 1#usize
    ok (cont (result1, power1, i1))
  else ok (done result)

/-- [bijou64::tier_offset]: loop 0:
    Source: 'bijou64/src/lib.rs', lines 107:4-111:5 -/
@[rust_loop]
def tier_offset_loop
  (n : Std.Usize) (result : Std.U64) (power : Std.U64) (i : Std.Usize) :
  Result Std.U64
  := do
  loop
    (fun (result1, power1, i1) => tier_offset_loop.body n result1 power1 i1)
    (result, power, i)

/-- [bijou64::tier_offset]:
    Source: 'bijou64/src/lib.rs', lines 96:0-113:1 -/
def tier_offset (n : Std.Usize) : Result Std.U64 := do
  if n = 0#usize
  then ok 0#u64
  else
    if n = 1#usize
    then ok (UScalar.cast .U64 TAG_THRESHOLD)
    else
      let result ← lift (UScalar.cast .U64 TAG_THRESHOLD)
      tier_offset_loop n result 1#u64 2#usize

/-- [bijou64::OFFSETS]
    Source: 'bijou64/src/lib.rs', lines 119:0-129:2 -/
@[global_simps, irreducible]
def OFFSETS : Result (Array Std.U64 9#usize) := do
  let i ← tier_offset 0#usize
  let i1 ← tier_offset 1#usize
  let i2 ← tier_offset 2#usize
  let i3 ← tier_offset 3#usize
  let i4 ← tier_offset 4#usize
  let i5 ← tier_offset 5#usize
  let i6 ← tier_offset 6#usize
  let i7 ← tier_offset 7#usize
  let i8 ← tier_offset 8#usize
  ok (Array.make 9#usize [ i, i1, i2, i3, i4, i5, i6, i7, i8 ])

/-- [bijou64::BOUNDS]
    Source: 'bijou64/src/lib.rs', lines 136:0-146:2 -/
@[global_simps, irreducible]
def BOUNDS : Result (Array Std.U64 9#usize) := do
  let i ← tier_offset 1#usize
  let i1 ← tier_offset 2#usize
  let i2 ← tier_offset 3#usize
  let i3 ← tier_offset 4#usize
  let i4 ← tier_offset 5#usize
  let i5 ← tier_offset 6#usize
  let i6 ← tier_offset 7#usize
  let i7 ← tier_offset 8#usize
  ok (Array.make 9#usize [ i, i1, i2, i3, i4, i5, i6, i7, core.num.U64.MAX ])

/-- [bijou64::encoded_len]:
    Source: 'bijou64/src/lib.rs', lines 168:0-198:1
    Visibility: public -/
def encoded_len (value : Std.U64) : Result Std.Usize := do
  let a ← BOUNDS
  let i ← Array.index_usize a 0#usize
  if value < i
  then ok 1#usize
  else
    let i1 ← lift (core.num.U64.leading_zeros value)
    let bw ← 64#u32 - i1
    let i2 ← bw - 1#u32
    let i3 ← i2 / 8#u32
    let i4 ← i3 + 2#u32
    let candidate ← lift (UScalar.cast .Usize i4)
    let i5 ← candidate - 2#usize
    let i6 ← Array.index_usize a i5
    if value < i6
    then candidate - 1#usize
    else ok candidate

/-- [bijou64::encode]:
    Source: 'bijou64/src/lib.rs', lines 214:0-233:1
    Visibility: public -/
def encode
  (value : Std.U64) (buf : alloc.vec.Vec Std.U8) :
  Result (alloc.vec.Vec Std.U8)
  := do
  let a ← BOUNDS
  let i ← Array.index_usize a 0#usize
  if value < i
  then
    let i1 ← lift (value &&& 255#u64)
    let i2 ← lift (UScalar.cast .U8 i1)
    alloc.vec.Vec.push buf i2
  else
    let i1 ← lift (core.num.U64.leading_zeros value)
    let bw ← 64#u32 - i1
    let i2 ← bw - 1#u32
    let i3 ← i2 / 8#u32
    let i4 ← i3 + 1#u32
    let tier ← lift (UScalar.cast .Usize i4)
    let i5 ← tier - 1#usize
    let i6 ← Array.index_usize a i5
    let tier1 ← if value < i6
                  then ok i5
                  else ok tier
    let i7 ← lift (UScalar.cast .Usize TAG_THRESHOLD)
    let i8 ← i7 + tier1
    let i9 ← i8 - 1#usize
    let tag ← lift (UScalar.cast .U8 i9)
    let a1 ← OFFSETS
    let i10 ← Array.index_usize a1 tier1
    let i11 ← value - i10
    let i12 ← NUM_TIERS - tier1
    let i13 ← 8#usize * i12
    let payload ← i11 <<< i13
    let pb ← lift (core.num.U64.to_be_bytes payload)
    let original_len := alloc.vec.Vec.len buf
    let i14 ← Array.index_usize pb 0#usize
    let i15 ← Array.index_usize pb 1#usize
    let i16 ← Array.index_usize pb 2#usize
    let i17 ← Array.index_usize pb 3#usize
    let i18 ← Array.index_usize pb 4#usize
    let i19 ← Array.index_usize pb 5#usize
    let i20 ← Array.index_usize pb 6#usize
    let i21 ← Array.index_usize pb 7#usize
    let s ←
      lift (Array.to_slice
        (Array.make 9#usize [ tag, i14, i15, i16, i17, i18, i19, i20, i21 ]))
    let buf1 ← alloc.vec.Vec.extend_from_slice core.clone.CloneU8 buf s
    let i22 ← original_len + tier1
    let i23 ← i22 + 1#usize
    alloc.vec.Vec.truncate Global buf1 i23

end BijouRust
