[package]
name = "bijou32_wasm"
version = "0.1.0"
description = "Wasm/JavaScript bindings for bijou32 (bijective varint encoding for u32)"

categories = ["encoding", "wasm", "web-programming"]
keywords = ["bijective", "canonical", "varint", "variable-length", "wasm"]
readme = "./README.md"
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bijou32 = { workspace = true }
js-sys = { workspace = true }
thiserror = { workspace = true }
wasm-bindgen = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }

[features]
default = ["std"]
std = [
  "js-sys/std",
  "thiserror/std",
  "wasm-bindgen/std",
]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O4", "--all-features"]

[lints]
workspace = true
